### ISSUE TITLE
Real time processing

### ISSUE THREAD

**Issue by SonNguyen2510** [haofanwang/CLIFF#12]
Dear author,

Thank you for your amazing work.
Is your method able to run in real-time?
I try to run your demo but there is error in mmdetection config file:
`    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'input_size'
`
Can you upload the config file for this detection model:
```
        config = './mmdetection/configs/yolox/yolox_x_8x8_300e_coco.py'
        checkpoint = './mmdetection/checkpoints/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth'
```

**Comment by moonbow721** [comment]
> Dear author,
> 
> Thank you for your amazing work. Is your method able to run in real-time? I try to run your demo but there is error in mmdetection config file: ` obj = obj_cls(**args) # type: ignore TypeError: __init__() got an unexpected keyword argument 'input_size'` Can you upload the config file for this detection model:
> 
> ```
>         config = './mmdetection/configs/yolox/yolox_x_8x8_300e_coco.py'
>         checkpoint = './mmdetection/checkpoints/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth'
> ```

Hi, I have encountered this error before.
This may be related to the version of mmdetection (try to use an older version).
The following versions work with torch 1.12.1 on my environment.
mmcv-full              1.7.1
mmdet                  2.26.0
mmengine               0.8.4
